language: csharp
solution: Mono.sln
install:
  - nuget restore Mono.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Mono.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Portable.Tests/bin/Release/Portable.Tests.dll
